workflows:
  ios-release:
    name: iOS Release Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'master'
          include: true
    scripts:
      - name: Install CocoaPods dependencies
        script: | 
          cd ios && pod install
      - name: Flutter build iOS
        script: | 
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
