// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
//
// ⚠️ קובץ זמני — הרץ: flutterfire configure
// הפקודה תחליף את הקובץ בערכים האמיתיים מפרויקט Firebase שלך.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyAe23k8LxQrKe-GbuOra3MBhhIHrlZhU',
    appId: '1:880133437316:web:009270fcc13f1628250fd1',
    messagingSenderId: '880133437316',
    projectId: 'myworkout-f6236',
    authDomain: 'myworkout-f6236.firebaseapp.com',
    storageBucket: 'myworkout-f6236.firebasestorage.app',
    measurementId: 'G-3XQY01WN4T',
  );

  // החלף את הערכים האלה באמצעות `flutterfire configure`, או מעתיק מהקונסול של Firebase.

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8LwsO8s1RwrjgG7ot__qxZVg4AYLlNaU',
    appId: '1:880133437316:android:76efc32eda10b4c4250fd1',
    messagingSenderId: '880133437316',
    projectId: 'myworkout-f6236',
    storageBucket: 'myworkout-f6236.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLFcn9nldYo_TRdEbcB8nMgLq_JaKZsQs',
    appId: '1:880133437316:ios:36f7a9316860173b250fd1',
    messagingSenderId: '880133437316',
    projectId: 'myworkout-f6236',
    storageBucket: 'myworkout-f6236.firebasestorage.app',
    iosBundleId: 'com.itay.myworkout',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'REPLACE_ME',
    storageBucket: 'REPLACE_ME.appspot.com',
    iosBundleId: 'com.itay.myworkout',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'REPLACE_ME',
    storageBucket: 'REPLACE_ME.appspot.com',
  );
}